// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package personal

import (
	"database/sql"
	"time"
)

type Personal struct {
	StaffID     int64          `json:"staff_id"`
	FullName    string         `json:"full_name"`
	RoleID      int32          `json:"role_id"`
	Department  sql.NullString `json:"department"`
	Phone       sql.NullString `json:"phone"`
	Email       sql.NullString `json:"email"`
	HiredAt     sql.NullTime   `json:"hired_at"`
	DismissedAt sql.NullTime   `json:"dismissed_at"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type StaffRole struct {
	RoleID int32  `json:"role_id"`
	Code   string `json:"code"`
	Name   string `json:"name"`
}
