// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package personal

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Personal struct {
	PersonalID   uuid.UUID      `json:"personal_id"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Phone        sql.NullString `json:"phone"`
	Status       string         `json:"status"`
	Departure    string         `json:"departure"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
