// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package staff_roles

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createStaffRoleStmt, err = db.PrepareContext(ctx, createStaffRole); err != nil {
		return nil, fmt.Errorf("error preparing query CreateStaffRole: %w", err)
	}
	if q.deleteStaffRoleStmt, err = db.PrepareContext(ctx, deleteStaffRole); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteStaffRole: %w", err)
	}
	if q.getStaffRoleStmt, err = db.PrepareContext(ctx, getStaffRole); err != nil {
		return nil, fmt.Errorf("error preparing query GetStaffRole: %w", err)
	}
	if q.getStaffRoleByCodeStmt, err = db.PrepareContext(ctx, getStaffRoleByCode); err != nil {
		return nil, fmt.Errorf("error preparing query GetStaffRoleByCode: %w", err)
	}
	if q.listStaffRolesStmt, err = db.PrepareContext(ctx, listStaffRoles); err != nil {
		return nil, fmt.Errorf("error preparing query ListStaffRoles: %w", err)
	}
	if q.updateStaffRoleStmt, err = db.PrepareContext(ctx, updateStaffRole); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateStaffRole: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createStaffRoleStmt != nil {
		if cerr := q.createStaffRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createStaffRoleStmt: %w", cerr)
		}
	}
	if q.deleteStaffRoleStmt != nil {
		if cerr := q.deleteStaffRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteStaffRoleStmt: %w", cerr)
		}
	}
	if q.getStaffRoleStmt != nil {
		if cerr := q.getStaffRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStaffRoleStmt: %w", cerr)
		}
	}
	if q.getStaffRoleByCodeStmt != nil {
		if cerr := q.getStaffRoleByCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getStaffRoleByCodeStmt: %w", cerr)
		}
	}
	if q.listStaffRolesStmt != nil {
		if cerr := q.listStaffRolesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listStaffRolesStmt: %w", cerr)
		}
	}
	if q.updateStaffRoleStmt != nil {
		if cerr := q.updateStaffRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateStaffRoleStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                     DBTX
	tx                     *sql.Tx
	createStaffRoleStmt    *sql.Stmt
	deleteStaffRoleStmt    *sql.Stmt
	getStaffRoleStmt       *sql.Stmt
	getStaffRoleByCodeStmt *sql.Stmt
	listStaffRolesStmt     *sql.Stmt
	updateStaffRoleStmt    *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                     tx,
		tx:                     tx,
		createStaffRoleStmt:    q.createStaffRoleStmt,
		deleteStaffRoleStmt:    q.deleteStaffRoleStmt,
		getStaffRoleStmt:       q.getStaffRoleStmt,
		getStaffRoleByCodeStmt: q.getStaffRoleByCodeStmt,
		listStaffRolesStmt:     q.listStaffRolesStmt,
		updateStaffRoleStmt:    q.updateStaffRoleStmt,
	}
}
