// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package staff_roles

type StaffRole struct {
	RoleID int32  `json:"role_id"`
	Code   string `json:"code"`
	Name   string `json:"name"`
}
